packages:
  - "apps/*"
  - "packages/*"

catalog:
  next: 15.5.18
  react: 19.1.0
  react-dom: 19.1.0
  typescript: ^5.7.3
  "@types/node": ^20
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@tailwindcss/postcss": ^4
  tailwindcss: ^4
